config/routes.rb
Tincanz::Engine.routes.draw do
  
  resources :users, only: [:index, :show]
  resources :conversations, only: [:index, :show, :new, :create] do
    resource   :assignee, only: :update, controller: 'assignees'
    resources :messages, only: [:new, :create]
  end

end

app/models/tincanz/conversation.rb
module Tincanz
  class Conversation < ActiveRecord::Base

    belongs_to :assignee, 
               foreign_key: :user_id,
               class_name: Tincanz.user_class
    
    has_many :messages, class_name: 'Tincanz::Message'

    has_many :receipts, 
             through: :messages

    has_many :recipients,
             -> { uniq },
             through: :receipts,
             class_name: Tincanz.user_class
    
    has_many :authors,
             -> { uniq },
             through: :messages,
             source: :user,
             class_name: Tincanz.user_class

    has_one  :first_message, 
             -> { order('tincanz_messages.created_at ASC').limit(1) },
             class_name: 'Tincanz::Message'

    has_many :subsequent_messages,
              -> { order('tincanz_messages.created_at ASC').offset(1) },
             class_name: 'Tincanz::Message'              

    has_one  :most_recent_message,
             -> { order('tincanz_messages.created_at DESC').limit(1) },
             class_name: 'Tincanz::Message'         


    scope :involving, -> (user) { joins(messages: :receipts).where(["tincanz_messages.user_id = :user_id OR tincanz_receipts.recipient_id = :user_id", user_id: user.id]).uniq }

    scope :recent, -> { order('created_at DESC') }

    accepts_nested_attributes_for :messages

    belongs_to :user, class_name: Tincanz.user_class

    def participants
      (authors + recipients).uniq
    end
  end
end

app/models/tincanz/conversation_composer.rb
# Creates new conversation with first message from params
# Allows admin to create with multiple recipients but 
# ensures user initiated messages are always sent to admin 
# and not other users.

module Tincanz
  class ConversationComposer

    delegate :recipient_ids, :content, :user, to: :message

    def self.compose(user, params)
      new(user, params).compose
    end

    def initialize(user, params)
      @user = user
      @params = params
    end

    def compose
      conversation = Conversation.new(@params)
      message = conversation.messages.first

      message.user = @user
      message.recipients = Tincanz.user_class.tincanz_admin unless @user.can_manage_tincanz?
      conversation.messages = [message] # HACK - prevent user from created multiple nested attribute records.

      conversation
    end
  end
end

app/models/tincanz/conversation_stream.rb
module Tincanz

  class ConversationStream

    def initialize(user, conversation)
      @user = user
      @conversation = conversation
    end

    def first_message
      messages.first
    end

    def subsequent_messages
      messages[1..-1]
    end

    private

    def messages
      @user.can_manage_tincanz? ? @conversation.messages : @conversation.messages.involving(@user)
    end

  end

end

app/models/tincanz/inbox.rb
module Tincanz
  class Inbox
    def initialize(user, params)
      @user = user
      @current_filter = params[:tab] || 'All'
    end

    def conversations
      if @user.can_manage_tincanz?
        return filtered
      else
        Conversation.involving(@user)
      end
    end
    
    def filtered
      return case @current_filter
      when 'All' then all
      when 'Yours' then yours
      when 'Nobody' then nobody
      else 
        raise @current_filter.inspect
      end
    end

    def all
      Conversation.all
    end

    def yours
      Conversation.where(user_id: @user.id)
    end

    def nobody
      Conversation.where(user_id: nil)
    end
  end

end

app/models/tincanz/message.rb
module Tincanz
  class Message < ActiveRecord::Base

    belongs_to :conversation, 
               class_name: 'Tincanz::Conversation'

    belongs_to :user, 
               class_name: Tincanz.user_class

    belongs_to :reply_to, 
               class_name: 'Tincanz::Message'

    has_many   :replies, 
               class_name: 'Tincanz::Message',
               foreign_key: 'reply_to_id'

    has_many   :receipts,
               class_name: 'Tincanz::Receipt'

    has_many   :recipients,
               class_name: Tincanz.user_class,
               through: :receipts

    scope :recent, -> { order 'created_at DESC' }

    scope :most_recent, -> { recent.limit(1).first }

    scope :involving, -> (user) { joins(:receipts).where(["tincanz_messages.user_id = :user_id OR tincanz_receipts.recipient_id = :user_id", user_id: user.id]) }

    validates :user, presence: true
    validates :content, presence: true


    def recipient_ids_string=(val)
      self.recipient_ids = val.is_a?(String) ? val.split(",") : val
    end
  end
end

app/models/tincanz/message_composer.rb
# Creates new message and when applicable inserts the contents
# of the message being replied to at the end of its content 

module Tincanz
  class MessageComposer
    def initialize(params)
      @message = Message.new(params)
    end

    def self.compose(params)
      new(params).compose
    end

    def compose
      if @message.reply_to
        @message.content << "\n\n------\n#{@message.reply_to.user.tincanz_email} wrote:\n#{@message.reply_to.content}"
      end
      @message
    end
  end
end

app/models/tincanz/receipt.rb
module Tincanz
  class Receipt < ActiveRecord::Base
    belongs_to :message, 
               class_name: 'Tincanz::Message'

    belongs_to :recipient, 
               class_name: Tincanz.user_class
               
  end
end

app/controllers/tincanz/admin/assignees_controller.rb
require_dependency "tincanz/application_controller"

module Tincanz
  class Admin::AssigneesController < ApplicationController
    before_filter :authenticate_tincanz_user
    before_filter :authorize_admin

    def update
      @conversation = Conversation.find(params[:conversation_id])

      if @conversation.update_attributes(conversation_params)
        flash.notice = t('tincanz.assignees.updated')
      else
        flash.alert  = t('tincanz.assignees.not_updated')
      end

      redirect_to admin_conversation_path(@conversation)
    end

    private

    def conversation_params
      params.require(:conversation).permit(:user_id)
    end 

  end
end

app/controllers/tincanz/admin/conversation_assignees_controller.rb
require_dependency "tincanz/application_controller"

module Tincanz
  class Admin::ConversationAssigneesController < ApplicationController
    before_filter :authenticate_tincanz_user
    before_filter :authorize_admin

    def update
      @conversation = Conversation.find(params[:conversation_id])

      if @conversation.update_attributes(conversation_params)
        flash.notice = t('tincanz.assignees.updated')
      else
        flash.alert  = t('tincanz.assignees.not_updated')
      end

      redirect_to admin_conversation_path(@conversation)
    end

    private

    def conversation_params
      params.require(:conversation).permit(:user_id)
    end 

  end
end

app/controllers/tincanz/admin/users_controller.rb
require_dependency "tincanz/application_controller"

module Tincanz
  class Admin::UsersController < ApplicationController
    before_filter :authenticate_tincanz_user
    before_filter :authorize_admin

    respond_to :html

    def index
      @users = Tincanz.user_class.all
      respond_with @users
    end

    def show
      @user = Tincanz.user_class.find(params[:id])
      respond_with @user
    end
  end
end

app/controllers/tincanz/application_controller.rb
class Tincanz::ApplicationController < ApplicationController
  
  rescue_from Tincanz::Unauthorized, with: :handle_unauthorized

  private

  def authorize!(permitted)
    raise Tincanz::Unauthorized unless permitted 
  end

  def handle_unauthorized
    flash.alert = t('tincanz.errors.unauthorized')
    redirect_to main_app.root_path
  end

  def authorize_admin
    authorize! tincanz_user.can_manage_tincanz?
  end

  def authenticate_tincanz_user
    if !tincanz_user
      flash.alert = t('tincanz.errors.unauthenticated')
      redirect_to sign_in_path
    end
  end

  def sign_in_path
    path = Tincanz.sign_in_path || (main_app.respond_to?(:sign_in_path) and main_app.sign_in_path)

    raise "Tincanz could not determine where to redirect your user to sign in." +
            "Either create a sign_in_path route in your main apps routes.rb or configure directly in a initializer file - Tincanz.sign_in_path = '/some/sign_in/path'" if !path
    
    path
  end
end

app/controllers/tincanz/assignees_controller.rb
require_dependency "tincanz/application_controller"

module Tincanz
  class AssigneesController < ApplicationController
    before_filter :authenticate_tincanz_user
    before_filter :authorize_admin

    def update
      @conversation = Conversation.find(params[:conversation_id])

      if @conversation.update_attributes(conversation_params)
        flash.notice = t('tincanz.assignees.updated')
      else
        flash.alert  = t('tincanz.assignees.not_updated')
      end

      redirect_to conversation_path(@conversation)
    end

    private

    def conversation_params
      params.require(:conversation).permit(:user_id)
    end 

  end
end

app/controllers/tincanz/conversations_controller.rb
require_dependency "tincanz/application_controller"

module Tincanz
  class ConversationsController < ApplicationController

    before_filter :authenticate_tincanz_user

    respond_to :html

    def index
      @conversations = Inbox.new(tincanz_user, params).conversations
      respond_with @conversations
    end

    def show
      @conversation = Conversation.find(params[:id])
      authorize! ConversationPolicy.new(tincanz_user, @conversation).can_read?
      @stream       = ConversationStream.new(tincanz_user, @conversation)
      respond_with @conversation
    end

    def new
      @conversation = Conversation.new
      @message      = @conversation.messages.build
      @message.recipient_ids = params[:recipient_ids]
      respond_with @conversation
    end

    def create
      @conversation = ConversationComposer.compose(tincanz_user, conversation_params)
    
      if @conversation.save
        flash.notice = t('tincanz.messages.created')
      else
        flash.alert  = t('tincanz.messages.not_created')
      end

      respond_with @conversation
    end

    private

    def conversation_params
      params.require(:conversation).permit(:messages_attributes => [[:content, :recipient_ids_string]])
    end
  end
end

app/controllers/tincanz/messages_controller.rb
require_dependency "tincanz/application_controller"

module Tincanz
  class MessagesController < ApplicationController

    before_filter :find_conversation
    before_filter :find_reply_to
    before_filter :authorize_conversation!
    before_filter :authorize_reply_to!

    respond_to :html

    def new
      @message = @conversation.messages.build(user: tincanz_user, 
                                              reply_to: @reply_to, 
                                              recipient_ids: [@reply_to.user.id], 
                                              content: "\n\n----\n\n#{@reply_to.content}")
      respond_with @message
    end

    def create
      @message  = @conversation.messages.build(message_params)
      @message.user = tincanz_user
    
      if @message.save
        flash.notice = t('tincanz.conversations.replied')
      else
        flash.alert = t('tincanz.conversations.not_replied')
      end

      respond_with @message do |f|
        f.html do
          @message.persisted? ? redirect_to(conversation_path(@conversation)) : render(action: :new)
        end
      end
    end

    private

    def find_conversation
      @conversation = Conversation.find(params[:conversation_id])
    end

    def find_reply_to
      @reply_to = Message.find(params[:reply_to_id] || message_params[:reply_to_id])
    end

    def authorize_conversation!
      authorize! ConversationPolicy.new(tincanz_user, @conversation).can_read?
    end

    def authorize_reply_to!
      authorize! ReplyPolicy.new(tincanz_user, @reply_to).can_reply?
    end

    def message_params
      params.require(:message).permit(:reply_to_id, :content, :recipient_ids_string)
    end
  end
end

app/controllers/tincanz/users_controller.rb
require_dependency "tincanz/application_controller"

module Tincanz
  class UsersController < ApplicationController
    before_filter :authenticate_tincanz_user
    before_filter :authorize_admin

    respond_to :html

    def index
      @users = Tincanz.user_class.all
      respond_with @users
    end

    def show
      @user = Tincanz.user_class.find(params[:id])
      respond_with @user
    end
  end
end

app/helpers/tincanz/application_helper.rb
module Tincanz
  module ApplicationHelper
  end
end

app/helpers/tincanz/conversations_helper.rb
module Tincanz
  module ConversationsHelper
  end
end

app/helpers/tincanz/messages_helper.rb
module Tincanz
  module MessagesHelper
  end
end

app/views/tincanz/conversations/_message_summary.html.erb
<div class="message">
  <div class="message-header">
    <div class="inner">
      <div class="meta">
        <%= message.created_at.strftime('%d/%m/%Y') %> <%= message.user.tincanz_email %>
      </div>
    </div>
  </div>
  <div class="message-body">
    <div class="inner">
      <%= message.content %>
    </div>
  </div>
</div>

app/views/tincanz/conversations/index.html.erb
<% if tincanz_user.can_manage_tincanz? %>
  <div class="inbox-toolbar">
    <%= content_tag :li, class: ('active' if params[:tab] == 'All' ) do %>
      <%= link_to t('tincanz.conversations.all'), conversations_path(tab: 'All') %>
    <% end %>

    <%= content_tag :li, class: ('active' if params[:tab] == 'Yours' ) do %>
      <%= link_to t('tincanz.conversations.yours'), conversations_path(tab: 'Yours') %>
    <% end %>

    <%= content_tag :li, class: ('active' if params[:tab] == 'Nobody' ) do %>
      <%= link_to t('tincanz.conversations.nobody'), conversations_path(tab: 'Nobody') %>
    <% end %>
  </div>
<% end %>

<div class="conversations-list">
  <div class="column">

    <% @conversations.each do |conversation| %>
      <%= content_tag_for :div, conversation do %>

        <a href="<%= conversation_path(conversation) %>">

          <div class="conversation-header">
            <div class="inner">
              <div class="messages-count">
                <span class="badge"><%= conversation.messages.count %></span>
              </div>
            </div>

          </div>
          
          <div class="message-stream">
            <%= render partial: 'tincanz/conversations/message_summary', object: conversation.first_message, as: :message %>

            <% subsequent = conversation.subsequent_messages.count %>

            <% if subsequent > 0 %>
              
              <% if subsequent > 2 %>
                <div class="message-collapsed"></div>
                <div class="message-collapsed"></div>      
              <% end %>

              <%= render partial: 'tincanz/conversations/message_summary', object: conversation.most_recent_message, as: :message %>        

            <% end %>          
          </div>
        <% end %>
      <% end %>
    <a>
  </div>
</div>

app/views/tincanz/conversations/new.html.erb
<h1>Send a message</h1>

<%= form_for @conversation do |f| %>

  <%= f.fields_for :messages do |m| %>
    
    <%= m.hidden_field :recipient_ids_string, value: m.object.recipient_ids.join(",") if tincanz_user.can_manage_tincanz? %>

    <div class="form-group">
      <label for="conversation_message_content">Content</label>
      <%= m.text_area :content, id: 'conversation_message_content' %>
    </div>

  <% end %>
  
  <%= f.submit t('tincanz.messages.create') %>
<% end %>

app/views/tincanz/conversations/show.html.erb
<div class="conversation-single">
  <div class="column">

    <% if tincanz_user.can_manage_tincanz? %>
      <%= form_for @conversation, url: conversation_assignee_path(@conversation), method: :put do |f| %>
        <label for="conversation_user_id"><%= t('tincanz.views.assigned_to') %></label>
        <%= f.collection_select :user_id, 
                                Tincanz.user_class.tincanz_admin, 
                                :id, 
                                :tincanz_email,
                                include_blank: t('tincanz.views.unassigned')
                                 %>
        <%= f.submit t('tincanz.forms.update') %>
      <% end %>
    <% end %>
    

    <div class="conversation-message">
      <%= render partial: 'tincanz/messages/message', object: @stream.first_message %>
      
    </div>

    <div class="conversation-replies">
      <div class="replies-list">
        <%= render partial: 'tincanz/messages/message', collection: @stream.subsequent_messages %>
      </div>
    </div>
  <div>
</div>